#
# Prune Settings
#

[prune]
  non-go = true
  unused-packages = true
  go-tests = true

#
# Constraints
#

# Cobra for CLI building - does not yet have semantic versioning
[[constraint]]
  name = "github.com/spf13/cobra"
  version = "v0.0.1"

# Viper for Configuration via files, env vars and CLI flags
[[constraint]]
  name = "github.com/spf13/viper"
  version = "v1.0.0"

# Structured logging
[[constraint]]
  name = "github.com/rs/zerolog"
  version = "v1.3.0"

# Kubernetets Client
[[constraint]]
  name = "k8s.io/client-go"
  version = "v6.0.0"

# gRPC server / client
[[constraint]]
  name = "google.golang.org/grpc"
  version = "v1.9.2"

# UUIDs
[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "v1.2.0"

# Postgres Database Driver
[[constraint]]
  name = "github.com/lib/pq"
  revision = "19c8e9ad00952ce0c64489b60e8df88bb16dd514"

# Extensions for databae/sql
[[constraint]]
  name = "github.com/jmoiron/sqlx"
  revision = "05cef0741ade10ca668982355b3f3f0bcf0ff0a8"

# Database migrations
[[constraint]]
  name = "github.com/mattes/migrate"
  version = "v3.0.1"

# Prompt
[[constraint]]
  name = "github.com/AlecAivazis/survey"
  version = "v1.5.1"
