// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/needle/v1/needle.proto

/*
Package needle is a generated protocol buffer package.

It is generated from these files:
	proto/needle/v1/needle.proto

It has these top-level messages:
	PutServiceRequest
	PutServiceResponse
	Service
*/
package needle

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Request for [PutService](compass.needle.v1.PutService)
type PutServiceRequest struct {
	// Service to be created or updated
	Service *Service `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"`
}

func (m *PutServiceRequest) Reset()                    { *m = PutServiceRequest{} }
func (m *PutServiceRequest) String() string            { return proto.CompactTextString(m) }
func (*PutServiceRequest) ProtoMessage()               {}
func (*PutServiceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PutServiceRequest) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

// Response for [PutService](compass.needle.v1.PutService)
type PutServiceResponse struct {
	// Service crated or updated
	Service *Service `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"`
}

func (m *PutServiceResponse) Reset()                    { *m = PutServiceResponse{} }
func (m *PutServiceResponse) String() string            { return proto.CompactTextString(m) }
func (*PutServiceResponse) ProtoMessage()               {}
func (*PutServiceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PutServiceResponse) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

// A Service is a service that compass is managing a namerd dentry for
type Service struct {
	// Id - the primary key - but not used for upserts
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// User created date
	CreateDate *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=create_date,json=createDate" json:"create_date,omitempty"`
	// User updated date
	UpdateDate *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=update_date,json=updateDate" json:"update_date,omitempty"`
	// The logical name, e.g HTTP/1.1 Host name or HTTP/2 :authority
	LogicalName string `protobuf:"bytes,4,opt,name=logical_name,json=logicalName" json:"logical_name,omitempty"`
	// The namerd namespace the service should be managed within
	Namespace string `protobuf:"bytes,5,opt,name=namespace" json:"namespace,omitempty"`
	// Optional description of the service
	Description string `protobuf:"bytes,6,opt,name=description" json:"description,omitempty"`
}

func (m *Service) Reset()                    { *m = Service{} }
func (m *Service) String() string            { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()               {}
func (*Service) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Service) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Service) GetCreateDate() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreateDate
	}
	return nil
}

func (m *Service) GetUpdateDate() *google_protobuf.Timestamp {
	if m != nil {
		return m.UpdateDate
	}
	return nil
}

func (m *Service) GetLogicalName() string {
	if m != nil {
		return m.LogicalName
	}
	return ""
}

func (m *Service) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Service) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*PutServiceRequest)(nil), "compass.needle.v1.PutServiceRequest")
	proto.RegisterType((*PutServiceResponse)(nil), "compass.needle.v1.PutServiceResponse")
	proto.RegisterType((*Service)(nil), "compass.needle.v1.Service")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ServiceManager service

type ServiceManagerClient interface {
	// PutService upserts services to be managed
	PutService(ctx context.Context, in *PutServiceRequest, opts ...grpc.CallOption) (*PutServiceResponse, error)
}

type serviceManagerClient struct {
	cc *grpc.ClientConn
}

func NewServiceManagerClient(cc *grpc.ClientConn) ServiceManagerClient {
	return &serviceManagerClient{cc}
}

func (c *serviceManagerClient) PutService(ctx context.Context, in *PutServiceRequest, opts ...grpc.CallOption) (*PutServiceResponse, error) {
	out := new(PutServiceResponse)
	err := grpc.Invoke(ctx, "/compass.needle.v1.ServiceManager/PutService", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ServiceManager service

type ServiceManagerServer interface {
	// PutService upserts services to be managed
	PutService(context.Context, *PutServiceRequest) (*PutServiceResponse, error)
}

func RegisterServiceManagerServer(s *grpc.Server, srv ServiceManagerServer) {
	s.RegisterService(&_ServiceManager_serviceDesc, srv)
}

func _ServiceManager_PutService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServer).PutService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/compass.needle.v1.ServiceManager/PutService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServer).PutService(ctx, req.(*PutServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServiceManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "compass.needle.v1.ServiceManager",
	HandlerType: (*ServiceManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutService",
			Handler:    _ServiceManager_PutService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/needle/v1/needle.proto",
}

func init() { proto.RegisterFile("proto/needle/v1/needle.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0xdd, 0xd4, 0x8d, 0xbd, 0xca, 0x70, 0x39, 0x95, 0x31, 0x70, 0x0e, 0x05, 0x4f, 0x2d,
	0x9b, 0xde, 0x76, 0x13, 0x2f, 0x0a, 0x8a, 0x4c, 0x4f, 0x7a, 0x18, 0x59, 0xf2, 0x2c, 0x81, 0xa6,
	0x89, 0x4d, 0xda, 0x3f, 0xdd, 0xb3, 0x2c, 0x49, 0xb7, 0xc1, 0x84, 0x81, 0xb7, 0xf0, 0xbd, 0xef,
	0xf7, 0xd1, 0xef, 0xbd, 0xc2, 0x48, 0x97, 0xca, 0xaa, 0xb4, 0x40, 0xe4, 0x39, 0xa6, 0xf5, 0x34,
	0xbc, 0x12, 0x27, 0x93, 0x01, 0x53, 0x52, 0x53, 0x63, 0x92, 0xa0, 0xd6, 0xd3, 0xe1, 0x45, 0xa6,
	0x54, 0x96, 0x63, 0xea, 0x0c, 0xab, 0xea, 0x2b, 0xb5, 0x42, 0xa2, 0xb1, 0x54, 0x6a, 0xcf, 0x4c,
	0x1e, 0x61, 0xf0, 0x5a, 0xd9, 0x37, 0x2c, 0x6b, 0xc1, 0x70, 0x81, 0xdf, 0x15, 0x1a, 0x4b, 0xee,
	0xa0, 0x6b, 0xbc, 0x12, 0xb7, 0xc6, 0xad, 0x9b, 0x68, 0x36, 0x4c, 0xf6, 0xa2, 0x93, 0x86, 0x69,
	0xac, 0x93, 0x27, 0x20, 0xbb, 0x51, 0x46, 0xab, 0xc2, 0xe0, 0x3f, 0xb3, 0x7e, 0x5a, 0xd0, 0x0d,
	0x22, 0xe9, 0x43, 0x5b, 0x70, 0x07, 0xf7, 0x16, 0x6d, 0xc1, 0xc9, 0x1c, 0x22, 0x56, 0x22, 0xb5,
	0xb8, 0xe4, 0xd4, 0x62, 0xdc, 0x0e, 0xa9, 0xbe, 0x69, 0xd2, 0x34, 0x4d, 0xde, 0x9b, 0xa6, 0x0b,
	0xf0, 0xf6, 0x07, 0x6a, 0x71, 0x0d, 0x57, 0x9a, 0x6f, 0xe0, 0xe3, 0xc3, 0xb0, 0xb7, 0x3b, 0xf8,
	0x12, 0xce, 0x72, 0x95, 0x09, 0x46, 0xf3, 0x65, 0x41, 0x25, 0xc6, 0x27, 0xee, 0x9b, 0xa2, 0xa0,
	0xbd, 0x50, 0x89, 0x64, 0x04, 0xbd, 0xf5, 0xc8, 0x68, 0xca, 0x30, 0x3e, 0x75, 0xf3, 0xad, 0x40,
	0xc6, 0x10, 0x71, 0x34, 0xac, 0x14, 0xda, 0x0a, 0x55, 0xc4, 0x1d, 0xcf, 0xef, 0x48, 0x33, 0x09,
	0xfd, 0xd0, 0xfb, 0x99, 0x16, 0x34, 0xc3, 0x92, 0x7c, 0x02, 0x6c, 0xd7, 0x4a, 0xae, 0xfe, 0xd8,
	0xde, 0xde, 0x01, 0x87, 0xd7, 0x07, 0x5c, 0xfe, 0x36, 0x93, 0xa3, 0x7b, 0xf2, 0x71, 0xbe, 0xf9,
	0x99, 0xe6, 0xfe, 0xb5, 0xea, 0xb8, 0x2d, 0xdc, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x00, 0x7f,
	0xaf, 0xd4, 0x6d, 0x02, 0x00, 0x00,
}
