// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/needle.proto

/*
Package services is a generated protocol buffer package.

It is generated from these files:
	services/needle.proto

It has these top-level messages:
	DataMigrationUpgradeRequest
	DataMigrationUpgradeResponse
	DataMigrationVersionRequest
	DataMigrationVersionResponse
	Service
	DelegationTable
	Dentry
	PutServiceRequest
	PutServiceResponse
	PutDentryRequest
	PutDentryResponse
	RouteToVersionRequest
	RouteToVersionResponse
	DeleteDentryByIdRequest
	DeleteDentryByIdResponse
	DeleteDentryByPrefixRequest
	DeleteDentryByPrefixResponse
	DelegationTablesRequest
	DelegationTablesResponse
	DentriesRequest
	DentriesResponse
*/
package services

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Request for [Upgrade](services.migration.DataMigrationService.Upgrade)
type DataMigrationUpgradeRequest struct {
}

func (m *DataMigrationUpgradeRequest) Reset()                    { *m = DataMigrationUpgradeRequest{} }
func (m *DataMigrationUpgradeRequest) String() string            { return proto.CompactTextString(m) }
func (*DataMigrationUpgradeRequest) ProtoMessage()               {}
func (*DataMigrationUpgradeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Response for [Upgrade](services.migration.DataMigrationService.Upgrade)
type DataMigrationUpgradeResponse struct {
	Ok bool `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
}

func (m *DataMigrationUpgradeResponse) Reset()                    { *m = DataMigrationUpgradeResponse{} }
func (m *DataMigrationUpgradeResponse) String() string            { return proto.CompactTextString(m) }
func (*DataMigrationUpgradeResponse) ProtoMessage()               {}
func (*DataMigrationUpgradeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DataMigrationUpgradeResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

// Request for [Version](services.migration.DataMigrationService.Version)
type DataMigrationVersionRequest struct {
}

func (m *DataMigrationVersionRequest) Reset()                    { *m = DataMigrationVersionRequest{} }
func (m *DataMigrationVersionRequest) String() string            { return proto.CompactTextString(m) }
func (*DataMigrationVersionRequest) ProtoMessage()               {}
func (*DataMigrationVersionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// Response for [Version](services.migration.DataMigrationService.Version)
type DataMigrationVersionResponse struct {
	// Schema version
	Version string `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
}

func (m *DataMigrationVersionResponse) Reset()                    { *m = DataMigrationVersionResponse{} }
func (m *DataMigrationVersionResponse) String() string            { return proto.CompactTextString(m) }
func (*DataMigrationVersionResponse) ProtoMessage()               {}
func (*DataMigrationVersionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DataMigrationVersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

// A Service is a service that compass is managing a namerd dentry for
type Service struct {
	// Id - the primary key - but not used for upserts
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// User created date
	CreateDate *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=create_date,json=createDate" json:"create_date,omitempty"`
	// User updated date
	UpdateDate *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=update_date,json=updateDate" json:"update_date,omitempty"`
	// The logical name, e.g HTTP/1.1 Host name or HTTP/2 :authority
	LogicalName string `protobuf:"bytes,4,opt,name=logical_name,json=logicalName" json:"logical_name,omitempty"`
	// The kubernetets namespace the app runs in
	Namespace string `protobuf:"bytes,5,opt,name=namespace" json:"namespace,omitempty"`
	// Optional description of the service
	Description string `protobuf:"bytes,6,opt,name=description" json:"description,omitempty"`
}

func (m *Service) Reset()                    { *m = Service{} }
func (m *Service) String() string            { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()               {}
func (*Service) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Service) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Service) GetCreateDate() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreateDate
	}
	return nil
}

func (m *Service) GetUpdateDate() *google_protobuf.Timestamp {
	if m != nil {
		return m.UpdateDate
	}
	return nil
}

func (m *Service) GetLogicalName() string {
	if m != nil {
		return m.LogicalName
	}
	return ""
}

func (m *Service) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Service) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// A DelegationTable holds any number of dentries
type DelegationTable struct {
	// Name of the delegation table
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *DelegationTable) Reset()                    { *m = DelegationTable{} }
func (m *DelegationTable) String() string            { return proto.CompactTextString(m) }
func (*DelegationTable) ProtoMessage()               {}
func (*DelegationTable) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DelegationTable) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// A Dentry is a single Delegation Table Rule
type Dentry struct {
	// Id - the primary key - but not used for upserts
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// Optional description of the service
	ServiceId string `protobuf:"bytes,2,opt,name=service_id,json=serviceId" json:"service_id,omitempty"`
	// User created date
	CreateDate *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=create_date,json=createDate" json:"create_date,omitempty"`
	// User updated date
	UpdateDate *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=update_date,json=updateDate" json:"update_date,omitempty"`
	// The prefix to match on
	Prefix string `protobuf:"bytes,5,opt,name=prefix" json:"prefix,omitempty"`
	// The destination of the matched prefix
	Destination string `protobuf:"bytes,6,opt,name=destination" json:"destination,omitempty"`
	// The dentry dtab (k8s namespace)
	Dtab string `protobuf:"bytes,7,opt,name=dtab" json:"dtab,omitempty"`
	// Prioity of the dentry - affects the ordering within the delegation table
	Priority int32 `protobuf:"varint,8,opt,name=priority" json:"priority,omitempty"`
}

func (m *Dentry) Reset()                    { *m = Dentry{} }
func (m *Dentry) String() string            { return proto.CompactTextString(m) }
func (*Dentry) ProtoMessage()               {}
func (*Dentry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Dentry) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Dentry) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *Dentry) GetCreateDate() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreateDate
	}
	return nil
}

func (m *Dentry) GetUpdateDate() *google_protobuf.Timestamp {
	if m != nil {
		return m.UpdateDate
	}
	return nil
}

func (m *Dentry) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *Dentry) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *Dentry) GetDtab() string {
	if m != nil {
		return m.Dtab
	}
	return ""
}

func (m *Dentry) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

// Request for [PutService](compass.needle.v1.NeedleService.PutService)
type PutServiceRequest struct {
	// Service to be created or updated
	Service *Service `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"`
}

func (m *PutServiceRequest) Reset()                    { *m = PutServiceRequest{} }
func (m *PutServiceRequest) String() string            { return proto.CompactTextString(m) }
func (*PutServiceRequest) ProtoMessage()               {}
func (*PutServiceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *PutServiceRequest) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

// Response for [PutService](compass.needle.v1.NeedleService.PutService)
type PutServiceResponse struct {
	// Service crated or updated
	Service *Service `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"`
}

func (m *PutServiceResponse) Reset()                    { *m = PutServiceResponse{} }
func (m *PutServiceResponse) String() string            { return proto.CompactTextString(m) }
func (*PutServiceResponse) ProtoMessage()               {}
func (*PutServiceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *PutServiceResponse) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

// Request for [PutDentry](compass.needle.v1.NeedleService.PutDentry)
type PutDentryRequest struct {
	// Dentry to create or update
	Dentry *Dentry `protobuf:"bytes,1,opt,name=dentry" json:"dentry,omitempty"`
}

func (m *PutDentryRequest) Reset()                    { *m = PutDentryRequest{} }
func (m *PutDentryRequest) String() string            { return proto.CompactTextString(m) }
func (*PutDentryRequest) ProtoMessage()               {}
func (*PutDentryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *PutDentryRequest) GetDentry() *Dentry {
	if m != nil {
		return m.Dentry
	}
	return nil
}

// Response for [PutDentry](compass.needle.v1.NeedleService.PutDentry)
type PutDentryResponse struct {
	// Dentry crated or updated
	Dentry *Dentry `protobuf:"bytes,1,opt,name=dentry" json:"dentry,omitempty"`
}

func (m *PutDentryResponse) Reset()                    { *m = PutDentryResponse{} }
func (m *PutDentryResponse) String() string            { return proto.CompactTextString(m) }
func (*PutDentryResponse) ProtoMessage()               {}
func (*PutDentryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *PutDentryResponse) GetDentry() *Dentry {
	if m != nil {
		return m.Dentry
	}
	return nil
}

// Request for [RouteToVersion](compass.needle.v1.NeedleService.RouteToVersion)
type RouteToVersionRequest struct {
	// Logical name of the service to route
	LogicalName string `protobuf:"bytes,1,opt,name=logical_name,json=logicalName" json:"logical_name,omitempty"`
	// Version string of the kubernetets service to route too
	Version string `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
}

func (m *RouteToVersionRequest) Reset()                    { *m = RouteToVersionRequest{} }
func (m *RouteToVersionRequest) String() string            { return proto.CompactTextString(m) }
func (*RouteToVersionRequest) ProtoMessage()               {}
func (*RouteToVersionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *RouteToVersionRequest) GetLogicalName() string {
	if m != nil {
		return m.LogicalName
	}
	return ""
}

func (m *RouteToVersionRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

// Response for [RouteToVersion](compass.needle.v1.NeedleService.RouteToVersion)
type RouteToVersionResponse struct {
}

func (m *RouteToVersionResponse) Reset()                    { *m = RouteToVersionResponse{} }
func (m *RouteToVersionResponse) String() string            { return proto.CompactTextString(m) }
func (*RouteToVersionResponse) ProtoMessage()               {}
func (*RouteToVersionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

// Request for [DeleteDentryById](compass.needle.v1.NeedleService.DeleteDentryById)
type DeleteDentryByIdRequest struct {
	// Id of the dentry to delete
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteDentryByIdRequest) Reset()                    { *m = DeleteDentryByIdRequest{} }
func (m *DeleteDentryByIdRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteDentryByIdRequest) ProtoMessage()               {}
func (*DeleteDentryByIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *DeleteDentryByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Response for [DeleteDentryById](compass.needle.v1.NeedleService.DeleteDentryById)
type DeleteDentryByIdResponse struct {
	// Indicates if the dentry was deleted
	Deleted bool `protobuf:"varint,1,opt,name=deleted" json:"deleted,omitempty"`
}

func (m *DeleteDentryByIdResponse) Reset()                    { *m = DeleteDentryByIdResponse{} }
func (m *DeleteDentryByIdResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteDentryByIdResponse) ProtoMessage()               {}
func (*DeleteDentryByIdResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *DeleteDentryByIdResponse) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

// Request for [DeleteDentryByPrefix](compass.needle.v1.NeedleService.DeleteDentryByPrefix)
type DeleteDentryByPrefixRequest struct {
	// Deletegation table the dentry is in
	Dtab string `protobuf:"bytes,1,opt,name=dtab" json:"dtab,omitempty"`
	// The dentry predfix
	Prefix string `protobuf:"bytes,2,opt,name=prefix" json:"prefix,omitempty"`
}

func (m *DeleteDentryByPrefixRequest) Reset()                    { *m = DeleteDentryByPrefixRequest{} }
func (m *DeleteDentryByPrefixRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteDentryByPrefixRequest) ProtoMessage()               {}
func (*DeleteDentryByPrefixRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *DeleteDentryByPrefixRequest) GetDtab() string {
	if m != nil {
		return m.Dtab
	}
	return ""
}

func (m *DeleteDentryByPrefixRequest) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

// Response for [DeleteDentryByPrefix](compass.needle.v1.NeedleService.DeleteDentryByPrefix)
type DeleteDentryByPrefixResponse struct {
	// Indicates if the dentry was deleted
	Deleted bool `protobuf:"varint,1,opt,name=deleted" json:"deleted,omitempty"`
}

func (m *DeleteDentryByPrefixResponse) Reset()                    { *m = DeleteDentryByPrefixResponse{} }
func (m *DeleteDentryByPrefixResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteDentryByPrefixResponse) ProtoMessage()               {}
func (*DeleteDentryByPrefixResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *DeleteDentryByPrefixResponse) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

// Request for [DelegationTables](compass.needle.v1.NeedleService.DelegationTables)
type DelegationTablesRequest struct {
}

func (m *DelegationTablesRequest) Reset()                    { *m = DelegationTablesRequest{} }
func (m *DelegationTablesRequest) String() string            { return proto.CompactTextString(m) }
func (*DelegationTablesRequest) ProtoMessage()               {}
func (*DelegationTablesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

// Response for [DelegationTables](compass.needle.v1.NeedleService.DelegationTables)
type DelegationTablesResponse struct {
	// Delegation tables
	DelegationTables []*DelegationTable `protobuf:"bytes,1,rep,name=delegation_tables,json=delegationTables" json:"delegation_tables,omitempty"`
}

func (m *DelegationTablesResponse) Reset()                    { *m = DelegationTablesResponse{} }
func (m *DelegationTablesResponse) String() string            { return proto.CompactTextString(m) }
func (*DelegationTablesResponse) ProtoMessage()               {}
func (*DelegationTablesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *DelegationTablesResponse) GetDelegationTables() []*DelegationTable {
	if m != nil {
		return m.DelegationTables
	}
	return nil
}

// Request for [Dentries](compass.needle.v1.NeedleService.Dentries)
type DentriesRequest struct {
	// Delegation Tables to get Dentries for
	Dtab string `protobuf:"bytes,1,opt,name=dtab" json:"dtab,omitempty"`
}

func (m *DentriesRequest) Reset()                    { *m = DentriesRequest{} }
func (m *DentriesRequest) String() string            { return proto.CompactTextString(m) }
func (*DentriesRequest) ProtoMessage()               {}
func (*DentriesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *DentriesRequest) GetDtab() string {
	if m != nil {
		return m.Dtab
	}
	return ""
}

// Response for [DelegationTables](compass.needle.v1.NeedleService.DelegationTables)
type DentriesResponse struct {
	// Dentries in the delegation table
	Dentries []*Dentry `protobuf:"bytes,1,rep,name=dentries" json:"dentries,omitempty"`
}

func (m *DentriesResponse) Reset()                    { *m = DentriesResponse{} }
func (m *DentriesResponse) String() string            { return proto.CompactTextString(m) }
func (*DentriesResponse) ProtoMessage()               {}
func (*DentriesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *DentriesResponse) GetDentries() []*Dentry {
	if m != nil {
		return m.Dentries
	}
	return nil
}

func init() {
	proto.RegisterType((*DataMigrationUpgradeRequest)(nil), "services.needle.DataMigrationUpgradeRequest")
	proto.RegisterType((*DataMigrationUpgradeResponse)(nil), "services.needle.DataMigrationUpgradeResponse")
	proto.RegisterType((*DataMigrationVersionRequest)(nil), "services.needle.DataMigrationVersionRequest")
	proto.RegisterType((*DataMigrationVersionResponse)(nil), "services.needle.DataMigrationVersionResponse")
	proto.RegisterType((*Service)(nil), "services.needle.Service")
	proto.RegisterType((*DelegationTable)(nil), "services.needle.DelegationTable")
	proto.RegisterType((*Dentry)(nil), "services.needle.Dentry")
	proto.RegisterType((*PutServiceRequest)(nil), "services.needle.PutServiceRequest")
	proto.RegisterType((*PutServiceResponse)(nil), "services.needle.PutServiceResponse")
	proto.RegisterType((*PutDentryRequest)(nil), "services.needle.PutDentryRequest")
	proto.RegisterType((*PutDentryResponse)(nil), "services.needle.PutDentryResponse")
	proto.RegisterType((*RouteToVersionRequest)(nil), "services.needle.RouteToVersionRequest")
	proto.RegisterType((*RouteToVersionResponse)(nil), "services.needle.RouteToVersionResponse")
	proto.RegisterType((*DeleteDentryByIdRequest)(nil), "services.needle.DeleteDentryByIdRequest")
	proto.RegisterType((*DeleteDentryByIdResponse)(nil), "services.needle.DeleteDentryByIdResponse")
	proto.RegisterType((*DeleteDentryByPrefixRequest)(nil), "services.needle.DeleteDentryByPrefixRequest")
	proto.RegisterType((*DeleteDentryByPrefixResponse)(nil), "services.needle.DeleteDentryByPrefixResponse")
	proto.RegisterType((*DelegationTablesRequest)(nil), "services.needle.DelegationTablesRequest")
	proto.RegisterType((*DelegationTablesResponse)(nil), "services.needle.DelegationTablesResponse")
	proto.RegisterType((*DentriesRequest)(nil), "services.needle.DentriesRequest")
	proto.RegisterType((*DentriesResponse)(nil), "services.needle.DentriesResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for DataMigrationService service

type DataMigrationServiceClient interface {
	Upgrade(ctx context.Context, in *DataMigrationUpgradeRequest, opts ...grpc.CallOption) (*DataMigrationUpgradeResponse, error)
	Version(ctx context.Context, in *DataMigrationVersionRequest, opts ...grpc.CallOption) (*DataMigrationVersionResponse, error)
}

type dataMigrationServiceClient struct {
	cc *grpc.ClientConn
}

func NewDataMigrationServiceClient(cc *grpc.ClientConn) DataMigrationServiceClient {
	return &dataMigrationServiceClient{cc}
}

func (c *dataMigrationServiceClient) Upgrade(ctx context.Context, in *DataMigrationUpgradeRequest, opts ...grpc.CallOption) (*DataMigrationUpgradeResponse, error) {
	out := new(DataMigrationUpgradeResponse)
	err := grpc.Invoke(ctx, "/services.needle.DataMigrationService/Upgrade", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataMigrationServiceClient) Version(ctx context.Context, in *DataMigrationVersionRequest, opts ...grpc.CallOption) (*DataMigrationVersionResponse, error) {
	out := new(DataMigrationVersionResponse)
	err := grpc.Invoke(ctx, "/services.needle.DataMigrationService/Version", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DataMigrationService service

type DataMigrationServiceServer interface {
	Upgrade(context.Context, *DataMigrationUpgradeRequest) (*DataMigrationUpgradeResponse, error)
	Version(context.Context, *DataMigrationVersionRequest) (*DataMigrationVersionResponse, error)
}

func RegisterDataMigrationServiceServer(s *grpc.Server, srv DataMigrationServiceServer) {
	s.RegisterService(&_DataMigrationService_serviceDesc, srv)
}

func _DataMigrationService_Upgrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataMigrationUpgradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataMigrationServiceServer).Upgrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.needle.DataMigrationService/Upgrade",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataMigrationServiceServer).Upgrade(ctx, req.(*DataMigrationUpgradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataMigrationService_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataMigrationVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataMigrationServiceServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.needle.DataMigrationService/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataMigrationServiceServer).Version(ctx, req.(*DataMigrationVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DataMigrationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.needle.DataMigrationService",
	HandlerType: (*DataMigrationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upgrade",
			Handler:    _DataMigrationService_Upgrade_Handler,
		},
		{
			MethodName: "Version",
			Handler:    _DataMigrationService_Version_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/needle.proto",
}

// Client API for DentryService service

type DentryServiceClient interface {
	// PutService upserts services to be managed
	PutService(ctx context.Context, in *PutServiceRequest, opts ...grpc.CallOption) (*PutServiceResponse, error)
	// DelegationTables returns a list of delegation tables we are managing
	DelegationTables(ctx context.Context, in *DelegationTablesRequest, opts ...grpc.CallOption) (*DelegationTablesResponse, error)
	// Dentries returns for a dtab
	Dentries(ctx context.Context, in *DentriesRequest, opts ...grpc.CallOption) (*DentriesResponse, error)
	// PutDentry upserts dentries to be managed
	PutDentry(ctx context.Context, in *PutDentryRequest, opts ...grpc.CallOption) (*PutDentryResponse, error)
	// DeleteDentryById deletes a dentry by it's UUID
	DeleteDentryById(ctx context.Context, in *DeleteDentryByIdRequest, opts ...grpc.CallOption) (*DeleteDentryByIdResponse, error)
	// DeleteDentryByPrefix deletes a dentry by prefix within a dtab
	DeleteDentryByPrefix(ctx context.Context, in *DeleteDentryByPrefixRequest, opts ...grpc.CallOption) (*DeleteDentryByPrefixResponse, error)
	// RouteToVersion routes a specific logical name to a specifc lubernetets services
	// based on a services logicalName and version labels
	RouteToVersion(ctx context.Context, in *RouteToVersionRequest, opts ...grpc.CallOption) (*RouteToVersionResponse, error)
}

type dentryServiceClient struct {
	cc *grpc.ClientConn
}

func NewDentryServiceClient(cc *grpc.ClientConn) DentryServiceClient {
	return &dentryServiceClient{cc}
}

func (c *dentryServiceClient) PutService(ctx context.Context, in *PutServiceRequest, opts ...grpc.CallOption) (*PutServiceResponse, error) {
	out := new(PutServiceResponse)
	err := grpc.Invoke(ctx, "/services.needle.DentryService/PutService", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dentryServiceClient) DelegationTables(ctx context.Context, in *DelegationTablesRequest, opts ...grpc.CallOption) (*DelegationTablesResponse, error) {
	out := new(DelegationTablesResponse)
	err := grpc.Invoke(ctx, "/services.needle.DentryService/DelegationTables", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dentryServiceClient) Dentries(ctx context.Context, in *DentriesRequest, opts ...grpc.CallOption) (*DentriesResponse, error) {
	out := new(DentriesResponse)
	err := grpc.Invoke(ctx, "/services.needle.DentryService/Dentries", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dentryServiceClient) PutDentry(ctx context.Context, in *PutDentryRequest, opts ...grpc.CallOption) (*PutDentryResponse, error) {
	out := new(PutDentryResponse)
	err := grpc.Invoke(ctx, "/services.needle.DentryService/PutDentry", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dentryServiceClient) DeleteDentryById(ctx context.Context, in *DeleteDentryByIdRequest, opts ...grpc.CallOption) (*DeleteDentryByIdResponse, error) {
	out := new(DeleteDentryByIdResponse)
	err := grpc.Invoke(ctx, "/services.needle.DentryService/DeleteDentryById", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dentryServiceClient) DeleteDentryByPrefix(ctx context.Context, in *DeleteDentryByPrefixRequest, opts ...grpc.CallOption) (*DeleteDentryByPrefixResponse, error) {
	out := new(DeleteDentryByPrefixResponse)
	err := grpc.Invoke(ctx, "/services.needle.DentryService/DeleteDentryByPrefix", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dentryServiceClient) RouteToVersion(ctx context.Context, in *RouteToVersionRequest, opts ...grpc.CallOption) (*RouteToVersionResponse, error) {
	out := new(RouteToVersionResponse)
	err := grpc.Invoke(ctx, "/services.needle.DentryService/RouteToVersion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DentryService service

type DentryServiceServer interface {
	// PutService upserts services to be managed
	PutService(context.Context, *PutServiceRequest) (*PutServiceResponse, error)
	// DelegationTables returns a list of delegation tables we are managing
	DelegationTables(context.Context, *DelegationTablesRequest) (*DelegationTablesResponse, error)
	// Dentries returns for a dtab
	Dentries(context.Context, *DentriesRequest) (*DentriesResponse, error)
	// PutDentry upserts dentries to be managed
	PutDentry(context.Context, *PutDentryRequest) (*PutDentryResponse, error)
	// DeleteDentryById deletes a dentry by it's UUID
	DeleteDentryById(context.Context, *DeleteDentryByIdRequest) (*DeleteDentryByIdResponse, error)
	// DeleteDentryByPrefix deletes a dentry by prefix within a dtab
	DeleteDentryByPrefix(context.Context, *DeleteDentryByPrefixRequest) (*DeleteDentryByPrefixResponse, error)
	// RouteToVersion routes a specific logical name to a specifc lubernetets services
	// based on a services logicalName and version labels
	RouteToVersion(context.Context, *RouteToVersionRequest) (*RouteToVersionResponse, error)
}

func RegisterDentryServiceServer(s *grpc.Server, srv DentryServiceServer) {
	s.RegisterService(&_DentryService_serviceDesc, srv)
}

func _DentryService_PutService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DentryServiceServer).PutService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.needle.DentryService/PutService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DentryServiceServer).PutService(ctx, req.(*PutServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DentryService_DelegationTables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelegationTablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DentryServiceServer).DelegationTables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.needle.DentryService/DelegationTables",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DentryServiceServer).DelegationTables(ctx, req.(*DelegationTablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DentryService_Dentries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DentriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DentryServiceServer).Dentries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.needle.DentryService/Dentries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DentryServiceServer).Dentries(ctx, req.(*DentriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DentryService_PutDentry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutDentryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DentryServiceServer).PutDentry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.needle.DentryService/PutDentry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DentryServiceServer).PutDentry(ctx, req.(*PutDentryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DentryService_DeleteDentryById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDentryByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DentryServiceServer).DeleteDentryById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.needle.DentryService/DeleteDentryById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DentryServiceServer).DeleteDentryById(ctx, req.(*DeleteDentryByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DentryService_DeleteDentryByPrefix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDentryByPrefixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DentryServiceServer).DeleteDentryByPrefix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.needle.DentryService/DeleteDentryByPrefix",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DentryServiceServer).DeleteDentryByPrefix(ctx, req.(*DeleteDentryByPrefixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DentryService_RouteToVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteToVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DentryServiceServer).RouteToVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.needle.DentryService/RouteToVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DentryServiceServer).RouteToVersion(ctx, req.(*RouteToVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DentryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.needle.DentryService",
	HandlerType: (*DentryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutService",
			Handler:    _DentryService_PutService_Handler,
		},
		{
			MethodName: "DelegationTables",
			Handler:    _DentryService_DelegationTables_Handler,
		},
		{
			MethodName: "Dentries",
			Handler:    _DentryService_Dentries_Handler,
		},
		{
			MethodName: "PutDentry",
			Handler:    _DentryService_PutDentry_Handler,
		},
		{
			MethodName: "DeleteDentryById",
			Handler:    _DentryService_DeleteDentryById_Handler,
		},
		{
			MethodName: "DeleteDentryByPrefix",
			Handler:    _DentryService_DeleteDentryByPrefix_Handler,
		},
		{
			MethodName: "RouteToVersion",
			Handler:    _DentryService_RouteToVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/needle.proto",
}

func init() { proto.RegisterFile("services/needle.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 812 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xcb, 0x6e, 0xdb, 0x46,
	0x14, 0x15, 0x25, 0x5b, 0x8f, 0xab, 0xd6, 0x8f, 0x81, 0x1f, 0x2c, 0x6d, 0xa3, 0xf2, 0x14, 0x6d,
	0x65, 0xa0, 0xa5, 0x00, 0xb9, 0x8b, 0x02, 0xd9, 0x39, 0x02, 0x1c, 0x2f, 0x1c, 0x38, 0x8c, 0x92,
	0x00, 0xd9, 0x08, 0x94, 0x66, 0xac, 0x0c, 0x2c, 0x91, 0x0c, 0x39, 0x32, 0xe2, 0x6f, 0xc9, 0xe7,
	0xe4, 0x6f, 0xf2, 0x01, 0x59, 0x07, 0x9c, 0x07, 0x25, 0x3e, 0x24, 0xd9, 0xc9, 0x8e, 0x73, 0xef,
	0x9d, 0x73, 0xe7, 0x9e, 0x39, 0x73, 0x08, 0xfb, 0x11, 0x0d, 0xef, 0xd9, 0x88, 0x46, 0x1d, 0x8f,
	0x52, 0x32, 0xa1, 0x76, 0x10, 0xfa, 0xdc, 0x47, 0xdb, 0x3a, 0x6c, 0xcb, 0xb0, 0xf5, 0xfb, 0xd8,
	0xf7, 0xc7, 0x13, 0xda, 0x11, 0xe9, 0xe1, 0xec, 0xb6, 0xc3, 0xd9, 0x94, 0x46, 0xdc, 0x9d, 0x06,
	0x72, 0x07, 0x3e, 0x81, 0xa3, 0x9e, 0xcb, 0xdd, 0x6b, 0x36, 0x0e, 0x5d, 0xce, 0x7c, 0xef, 0x4d,
	0x30, 0x0e, 0x5d, 0x42, 0x1d, 0xfa, 0x71, 0x46, 0x23, 0x8e, 0x6d, 0x38, 0x2e, 0x4e, 0x47, 0x81,
	0xef, 0x45, 0x14, 0x6d, 0x41, 0xd9, 0xbf, 0x33, 0x8d, 0x96, 0xd1, 0xae, 0x3b, 0x65, 0xff, 0x2e,
	0x07, 0xf7, 0x96, 0x86, 0x11, 0xf3, 0x3d, 0x0d, 0xf7, 0x7f, 0x06, 0x2e, 0x49, 0x2b, 0x38, 0x13,
	0x6a, 0xf7, 0x32, 0x24, 0x30, 0x1b, 0x8e, 0x5e, 0xe2, 0x6f, 0x06, 0xd4, 0x5e, 0xcb, 0xe1, 0xe2,
	0xa6, 0x8c, 0xa8, 0x82, 0x32, 0x23, 0xe8, 0x19, 0x34, 0x47, 0x21, 0x75, 0x39, 0x1d, 0x10, 0x97,
	0x53, 0xb3, 0xdc, 0x32, 0xda, 0xcd, 0xae, 0x65, 0xcb, 0xd1, 0x6d, 0x3d, 0xba, 0xdd, 0xd7, 0xa3,
	0x3b, 0x20, 0xcb, 0x7b, 0x2e, 0xa7, 0xf1, 0xe6, 0x59, 0x40, 0x92, 0xcd, 0x95, 0xf5, 0x9b, 0x65,
	0xb9, 0xd8, 0x7c, 0x0a, 0xbf, 0x4c, 0xfc, 0x31, 0x1b, 0xb9, 0x93, 0x81, 0xe7, 0x4e, 0xa9, 0xb9,
	0x21, 0xce, 0xd4, 0x54, 0xb1, 0x97, 0xee, 0x94, 0xa2, 0x63, 0x68, 0xc4, 0xa9, 0x28, 0x70, 0x47,
	0xd4, 0xdc, 0x14, 0xf9, 0x79, 0x00, 0xb5, 0xa0, 0x49, 0x68, 0x34, 0x0a, 0x59, 0x10, 0xd3, 0x61,
	0x56, 0xe5, 0xfe, 0x85, 0x10, 0xfe, 0x13, 0xb6, 0x7b, 0x74, 0x42, 0xc7, 0x82, 0xaf, 0xbe, 0x3b,
	0x9c, 0x50, 0x84, 0x60, 0x43, 0x74, 0x93, 0x0c, 0x88, 0x6f, 0xfc, 0xb9, 0x0c, 0xd5, 0x1e, 0xf5,
	0x78, 0xf8, 0x90, 0xa3, 0xe7, 0x04, 0x40, 0xc9, 0x62, 0xc0, 0x88, 0x60, 0xa7, 0xe1, 0x34, 0x54,
	0xe4, 0x2a, 0xc7, 0x5e, 0xe5, 0x67, 0xd8, 0xdb, 0x78, 0x12, 0x7b, 0x07, 0x50, 0x0d, 0x42, 0x7a,
	0xcb, 0x3e, 0x29, 0x5e, 0xd4, 0x4a, 0x91, 0xc2, 0x99, 0xe7, 0x66, 0x48, 0xd1, 0xa1, 0x98, 0x01,
	0xc2, 0xdd, 0xa1, 0x59, 0x93, 0x0c, 0xc4, 0xdf, 0xc8, 0x82, 0x7a, 0x10, 0x32, 0x3f, 0x64, 0xfc,
	0xc1, 0xac, 0xb7, 0x8c, 0xf6, 0xa6, 0x93, 0xac, 0xf1, 0x25, 0xec, 0xde, 0xcc, 0xb8, 0xd2, 0x8f,
	0x12, 0x23, 0xea, 0x42, 0x4d, 0xb1, 0x20, 0xc8, 0x6a, 0x76, 0x4d, 0x3b, 0xf3, 0x7c, 0x6c, 0xbd,
	0x43, 0x17, 0xe2, 0x17, 0x80, 0x16, 0x81, 0x94, 0x6c, 0x7f, 0x04, 0xe9, 0x39, 0xec, 0xdc, 0xcc,
	0xb8, 0xbc, 0x32, 0x7d, 0xa2, 0x0e, 0x54, 0x89, 0x08, 0x28, 0x98, 0xc3, 0x1c, 0x8c, 0xaa, 0x57,
	0x65, 0xb8, 0x27, 0xe6, 0xd2, 0x20, 0xea, 0x34, 0x4f, 0x46, 0xe9, 0xc3, 0xbe, 0xe3, 0xcf, 0x38,
	0xed, 0xfb, 0xe9, 0xe7, 0x9a, 0x93, 0xb7, 0x91, 0x97, 0xf7, 0xc2, 0x8b, 0xad, 0xa4, 0x5f, 0xac,
	0x09, 0x07, 0x59, 0x54, 0x79, 0x40, 0x7c, 0x06, 0x87, 0xb1, 0xa4, 0x39, 0x95, 0xe7, 0xb8, 0x78,
	0xb8, 0x22, 0xba, 0x63, 0x46, 0xbb, 0xf8, 0x3f, 0x30, 0xf3, 0xa5, 0x73, 0xb3, 0x20, 0x22, 0x47,
	0x94, 0x01, 0xe9, 0x25, 0xbe, 0x82, 0xa3, 0xf4, 0xae, 0x1b, 0x21, 0x2c, 0xdd, 0x44, 0xab, 0xc7,
	0x58, 0x50, 0xcf, 0x5c, 0x8b, 0xe5, 0x45, 0x2d, 0x0a, 0xc7, 0x2a, 0x84, 0x5a, 0x7b, 0x88, 0xdf,
	0xe4, 0x94, 0x0b, 0x0f, 0x37, 0xd2, 0x36, 0xc8, 0xe4, 0x54, 0xe9, 0x94, 0x02, 0xbc, 0x86, 0x5d,
	0x92, 0xe4, 0x06, 0x5c, 0x24, 0x4d, 0xa3, 0x55, 0x69, 0x37, 0xbb, 0xad, 0x82, 0x8b, 0x4c, 0xa1,
	0x38, 0x3b, 0x24, 0x03, 0x2b, 0xed, 0xc3, 0xe3, 0x21, 0x4b, 0xba, 0x17, 0x8d, 0x8f, 0x2f, 0x61,
	0x67, 0x5e, 0xa6, 0x4e, 0x72, 0x0e, 0x75, 0xa2, 0x62, 0xea, 0x00, 0x4b, 0x95, 0x94, 0x14, 0x76,
	0xbf, 0x1a, 0xb0, 0x97, 0xb2, 0x78, 0x6d, 0xda, 0x1f, 0xa0, 0xa6, 0x7e, 0x1e, 0xe8, 0x9f, 0x3c,
	0xcc, 0xf2, 0x5f, 0x90, 0xf5, 0xef, 0x23, 0xab, 0x95, 0xb8, 0x4a, 0x71, 0x27, 0xa5, 0xb8, 0x75,
	0x9d, 0xd2, 0x72, 0x5f, 0xd7, 0x29, 0x2b, 0xe3, 0x52, 0xf7, 0xcb, 0x26, 0xfc, 0x2a, 0x19, 0xd0,
	0x53, 0xbe, 0x03, 0x98, 0xfb, 0x03, 0xc2, 0x39, 0xc0, 0x9c, 0x0b, 0x59, 0x7f, 0xac, 0xac, 0x49,
	0x86, 0x62, 0xf1, 0x05, 0xa5, 0xef, 0x16, 0xb5, 0xd7, 0xe9, 0x41, 0x5f, 0xb9, 0x75, 0xf6, 0x88,
	0xca, 0xa4, 0xd5, 0x2b, 0xa8, 0x6b, 0x2d, 0xa0, 0x56, 0xf1, 0x8d, 0xcf, 0xd5, 0x64, 0x9d, 0xae,
	0xa8, 0x48, 0x20, 0xfb, 0xd0, 0x48, 0x7c, 0x0a, 0x9d, 0x16, 0x4d, 0x9c, 0x32, 0x42, 0x0b, 0xaf,
	0x2a, 0xc9, 0x72, 0xb2, 0x68, 0x0e, 0x4b, 0x38, 0x29, 0xb0, 0x9a, 0x25, 0x9c, 0x14, 0x39, 0x0d,
	0x2e, 0xa1, 0x19, 0xec, 0x15, 0xd9, 0x40, 0x91, 0xc0, 0x96, 0x1b, 0x4f, 0x91, 0xc0, 0x56, 0x78,
	0x0b, 0x2e, 0xa1, 0x11, 0x6c, 0xa5, 0x3d, 0x14, 0xfd, 0x95, 0x83, 0x28, 0xb4, 0x6e, 0xeb, 0xef,
	0xb5, 0x75, 0xba, 0xc9, 0x05, 0xbc, 0xaf, 0xeb, 0xda, 0x61, 0x55, 0xfc, 0xb2, 0xcf, 0xbf, 0x07,
	0x00, 0x00, 0xff, 0xff, 0xad, 0xe4, 0x3b, 0xad, 0x60, 0x0a, 0x00, 0x00,
}
